<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-24T14:35:57 IST" name="Suite" finished-at="2022-07-24T14:36:55 IST" duration-ms="58073">
    <groups>
    </groups>
    <test started-at="2022-07-24T14:35:57 IST" name="Login" finished-at="2022-07-24T14:36:40 IST" duration-ms="42419">
      <class name="e2etesting.website.testcase">
        <test-method signature="launch(java.lang.String,java.lang.String)[pri:0, instance:e2etesting.website.testcase@461ad730]" started-at="2022-07-24T14:35:57 IST" name="launch" data-provider="dataprovider" finished-at="2022-07-24T14:36:18 IST" duration-ms="20373" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[abc]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[user]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
        <test-method signature="launch(java.lang.String,java.lang.String)[pri:0, instance:e2etesting.website.testcase@461ad730]" started-at="2022-07-24T14:36:18 IST" name="launch" data-provider="dataprovider" finished-at="2022-07-24T14:36:40 IST" duration-ms="21933" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[xyz]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[user2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch -->
      </class> <!-- e2etesting.website.testcase -->
    </test> <!-- Login -->
    <test started-at="2022-07-24T14:36:41 IST" name="Validate title" finished-at="2022-07-24T14:36:55 IST" duration-ms="14053">
      <class name="e2etesting.website.testcase2">
        <test-method signature="assertive()[pri:0, instance:e2etesting.website.testcase2@3cfdd820]" started-at="2022-07-24T14:36:41 IST" name="assertive" finished-at="2022-07-24T14:36:55 IST" duration-ms="14029" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Mismatch expected [FEATURED COURSS] but found [FEATURED COURSES]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Mismatch expected [FEATURED COURSS] but found [FEATURED COURSES]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at e2etesting.website.testcase2.assertive(testcase2.java:19)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- assertive -->
      </class> <!-- e2etesting.website.testcase2 -->
    </test> <!-- Validate title -->
  </suite> <!-- Suite -->
</testng-results>
